-- MySQL Script generated by MySQL Workbench
-- Mon Jul  7 19:40:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SchoolOnDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SchoolOnDb` ;

-- -----------------------------------------------------
-- Schema SchoolOnDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SchoolOnDb` DEFAULT CHARACTER SET utf8 ;
USE `SchoolOnDb` ;

-- -----------------------------------------------------
-- Table `SchoolOnDb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolOnDb`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SchoolOnDb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SchoolOnDb`.`post` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(60) NOT NULL,
  `conteudo` VARCHAR(1000) NULL,
  `data_criacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `imagem` VARCHAR(255) NULL,
  `data_atualizacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_post_usuario_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `SchoolOnDb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
